// Generated by gencpp from file my_ground_projection/EstimateHomography.msg
// DO NOT EDIT!


#ifndef MY_GROUND_PROJECTION_MESSAGE_ESTIMATEHOMOGRAPHY_H
#define MY_GROUND_PROJECTION_MESSAGE_ESTIMATEHOMOGRAPHY_H

#include <ros/service_traits.h>


#include <my_ground_projection/EstimateHomographyRequest.h>
#include <my_ground_projection/EstimateHomographyResponse.h>


namespace my_ground_projection
{

struct EstimateHomography
{

typedef EstimateHomographyRequest Request;
typedef EstimateHomographyResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct EstimateHomography
} // namespace my_ground_projection


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::my_ground_projection::EstimateHomography > {
  static const char* value()
  {
    return "d41d8cd98f00b204e9800998ecf8427e";
  }

  static const char* value(const ::my_ground_projection::EstimateHomography&) { return value(); }
};

template<>
struct DataType< ::my_ground_projection::EstimateHomography > {
  static const char* value()
  {
    return "my_ground_projection/EstimateHomography";
  }

  static const char* value(const ::my_ground_projection::EstimateHomography&) { return value(); }
};


// service_traits::MD5Sum< ::my_ground_projection::EstimateHomographyRequest> should match 
// service_traits::MD5Sum< ::my_ground_projection::EstimateHomography > 
template<>
struct MD5Sum< ::my_ground_projection::EstimateHomographyRequest>
{
  static const char* value()
  {
    return MD5Sum< ::my_ground_projection::EstimateHomography >::value();
  }
  static const char* value(const ::my_ground_projection::EstimateHomographyRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::my_ground_projection::EstimateHomographyRequest> should match 
// service_traits::DataType< ::my_ground_projection::EstimateHomography > 
template<>
struct DataType< ::my_ground_projection::EstimateHomographyRequest>
{
  static const char* value()
  {
    return DataType< ::my_ground_projection::EstimateHomography >::value();
  }
  static const char* value(const ::my_ground_projection::EstimateHomographyRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::my_ground_projection::EstimateHomographyResponse> should match 
// service_traits::MD5Sum< ::my_ground_projection::EstimateHomography > 
template<>
struct MD5Sum< ::my_ground_projection::EstimateHomographyResponse>
{
  static const char* value()
  {
    return MD5Sum< ::my_ground_projection::EstimateHomography >::value();
  }
  static const char* value(const ::my_ground_projection::EstimateHomographyResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::my_ground_projection::EstimateHomographyResponse> should match 
// service_traits::DataType< ::my_ground_projection::EstimateHomography > 
template<>
struct DataType< ::my_ground_projection::EstimateHomographyResponse>
{
  static const char* value()
  {
    return DataType< ::my_ground_projection::EstimateHomography >::value();
  }
  static const char* value(const ::my_ground_projection::EstimateHomographyResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // MY_GROUND_PROJECTION_MESSAGE_ESTIMATEHOMOGRAPHY_H
