// Generated by gencpp from file my_ground_projection/GetGroundCoord.msg
// DO NOT EDIT!


#ifndef MY_GROUND_PROJECTION_MESSAGE_GETGROUNDCOORD_H
#define MY_GROUND_PROJECTION_MESSAGE_GETGROUNDCOORD_H

#include <ros/service_traits.h>


#include <my_ground_projection/GetGroundCoordRequest.h>
#include <my_ground_projection/GetGroundCoordResponse.h>


namespace my_ground_projection
{

struct GetGroundCoord
{

typedef GetGroundCoordRequest Request;
typedef GetGroundCoordResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct GetGroundCoord
} // namespace my_ground_projection


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::my_ground_projection::GetGroundCoord > {
  static const char* value()
  {
    return "556869c22d708d07f00608b52f833756";
  }

  static const char* value(const ::my_ground_projection::GetGroundCoord&) { return value(); }
};

template<>
struct DataType< ::my_ground_projection::GetGroundCoord > {
  static const char* value()
  {
    return "my_ground_projection/GetGroundCoord";
  }

  static const char* value(const ::my_ground_projection::GetGroundCoord&) { return value(); }
};


// service_traits::MD5Sum< ::my_ground_projection::GetGroundCoordRequest> should match 
// service_traits::MD5Sum< ::my_ground_projection::GetGroundCoord > 
template<>
struct MD5Sum< ::my_ground_projection::GetGroundCoordRequest>
{
  static const char* value()
  {
    return MD5Sum< ::my_ground_projection::GetGroundCoord >::value();
  }
  static const char* value(const ::my_ground_projection::GetGroundCoordRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::my_ground_projection::GetGroundCoordRequest> should match 
// service_traits::DataType< ::my_ground_projection::GetGroundCoord > 
template<>
struct DataType< ::my_ground_projection::GetGroundCoordRequest>
{
  static const char* value()
  {
    return DataType< ::my_ground_projection::GetGroundCoord >::value();
  }
  static const char* value(const ::my_ground_projection::GetGroundCoordRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::my_ground_projection::GetGroundCoordResponse> should match 
// service_traits::MD5Sum< ::my_ground_projection::GetGroundCoord > 
template<>
struct MD5Sum< ::my_ground_projection::GetGroundCoordResponse>
{
  static const char* value()
  {
    return MD5Sum< ::my_ground_projection::GetGroundCoord >::value();
  }
  static const char* value(const ::my_ground_projection::GetGroundCoordResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::my_ground_projection::GetGroundCoordResponse> should match 
// service_traits::DataType< ::my_ground_projection::GetGroundCoord > 
template<>
struct DataType< ::my_ground_projection::GetGroundCoordResponse>
{
  static const char* value()
  {
    return DataType< ::my_ground_projection::GetGroundCoord >::value();
  }
  static const char* value(const ::my_ground_projection::GetGroundCoordResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // MY_GROUND_PROJECTION_MESSAGE_GETGROUNDCOORD_H
